-- Create Table
CREATE TABLE EMPLOYEE_SCORES (
    EMP_ID NUMBER,
    NAME VARCHAR2(50),
    DEPARTMENT VARCHAR2(30),
    SCORE NUMBER,
    REVIEW_DATE DATE
);

-- Insert Records (15 Rows Individually)
INSERT ALL
  INTO EMPLOYEE_SCORES VALUES (1, 'Aarav', 'Sales', 85, TO_DATE('2024-01-10', 'YYYY-MM-DD'))
  INTO EMPLOYEE_SCORES VALUES (2, 'Riya', 'HR', 75, TO_DATE('2024-01-12', 'YYYY-MM-DD'))
  INTO EMPLOYEE_SCORES VALUES (3, 'Karan', 'IT', 90, TO_DATE('2024-01-15', 'YYYY-MM-DD'))
  INTO EMPLOYEE_SCORES VALUES (4, 'Simran', 'Marketing', 80, TO_DATE('2024-01-18', 'YYYY-MM-DD'))
  INTO EMPLOYEE_SCORES VALUES (5, 'Dev', 'Sales', 88, TO_DATE('2024-02-01', 'YYYY-MM-DD'))
  INTO EMPLOYEE_SCORES VALUES (6, 'Neha', 'HR', 70, TO_DATE('2024-02-05', 'YYYY-MM-DD'))
  INTO EMPLOYEE_SCORES VALUES (7, 'Rohit', 'IT', 95, TO_DATE('2024-02-10', 'YYYY-MM-DD'))
  INTO EMPLOYEE_SCORES VALUES (8, 'Isha', 'Marketing', 60, TO_DATE('2024-02-15', 'YYYY-MM-DD'))
  INTO EMPLOYEE_SCORES VALUES (9, 'Aman', 'Sales', 77, TO_DATE('2024-02-20', 'YYYY-MM-DD'))
  INTO EMPLOYEE_SCORES VALUES (10, 'Tina', 'HR', 82, TO_DATE('2024-03-01', 'YYYY-MM-DD'))
  INTO EMPLOYEE_SCORES VALUES (11, 'Rahul', 'IT', 87, TO_DATE('2024-03-05', 'YYYY-MM-DD'))
  INTO EMPLOYEE_SCORES VALUES (12, 'Pooja', 'Marketing', 91, TO_DATE('2024-03-08', 'YYYY-MM-DD'))
  INTO EMPLOYEE_SCORES VALUES (13, 'Arjun', 'Sales', 65, TO_DATE('2024-03-10', 'YYYY-MM-DD'))
  INTO EMPLOYEE_SCORES VALUES (14, 'Sneha', 'HR', 89, TO_DATE('2024-03-15', 'YYYY-MM-DD'))
  INTO EMPLOYEE_SCORES VALUES (15, 'Vikram', 'IT', 78, TO_DATE('2024-03-20', 'YYYY-MM-DD'))
SELECT * FROM dual;


-- 1. Rank employees by SCORE within each DEPARTMENT
SELECT EMP_ID, NAME, DEPARTMENT, SCORE,
       RANK() OVER (PARTITION BY DEPARTMENT ORDER BY SCORE DESC) AS RANK_IN_DEPT
FROM EMPLOYEE_SCORES;

-- 2. Employees who scored above department average
SELECT * FROM EMPLOYEE_SCORES E
WHERE SCORE > (
    SELECT AVG(SCORE)
    FROM EMPLOYEE_SCORES
    WHERE DEPARTMENT = E.DEPARTMENT
);

-- 3. Top scorer in each department
SELECT * FROM (
    SELECT *, RANK() OVER (PARTITION BY DEPARTMENT ORDER BY SCORE DESC) AS RANK_IN_DEPT
    FROM EMPLOYEE_SCORES
) WHERE RANK_IN_DEPT = 1;

-- 4. Average score by department
SELECT DEPARTMENT, ROUND(AVG(SCORE), 2) AS AVG_SCORE
FROM EMPLOYEE_SCORES
GROUP BY DEPARTMENT;

-- 5. Monthly average score trend
SELECT TO_CHAR(REVIEW_DATE, 'YYYY-MM') AS MONTH, ROUND(AVG(SCORE), 2) AS AVG_SCORE
FROM EMPLOYEE_SCORES
GROUP BY TO_CHAR(REVIEW_DATE, 'YYYY-MM')
ORDER BY MONTH;

-- 6. Employees who scored above overall average
SELECT * FROM EMPLOYEE_SCORES
WHERE SCORE > (SELECT AVG(SCORE) FROM EMPLOYEE_SCORES);

-- 7. Department-wise score distribution
SELECT DEPARTMENT, SCORE, COUNT(*) AS NUM_EMPLOYEES
FROM EMPLOYEE_SCORES
GROUP BY DEPARTMENT, SCORE
ORDER BY DEPARTMENT, SCORE DESC;
